meta_product_name: "Col."
meta_title: "Col. | Trouvez votre colocation"
meta_description: "Col. vous permets de trouver facilement la colocation idéale qui répond rapidement à vos besoins "
meta_image: "col3.png" # should exist in `app/assets/images/`
 # twitter_account: "@product_twitter_account"